# Generated by Django 5.0.6 on 2025-03-22 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_name", models.CharField(max_length=100)),
                ("founder_name", models.CharField(max_length=100)),
                ("mobile_number", models.CharField(max_length=15)),
                ("image", models.ImageField(upload_to="lost_items/")),
                ("description", models.TextField()),
                ("colors", models.CharField(blank=True, max_length=200)),
                ("brand_name", models.CharField(blank=True, max_length=100)),
                ("where_found", models.CharField(max_length=200)),
                ("date_found", models.DateField()),
                ("time_found", models.CharField(max_length=10)),
                ("place_of_collection", models.CharField(max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claimant_name", models.CharField(max_length=100)),
                ("proof", models.ImageField(upload_to="claims/")),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lostfound.lostitem",
                    ),
                ),
            ],
        ),
    ]
