# Generated by Django 5.1.7 on 2025-03-22 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0003_rename_item_claim_lost_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitem',
            name='founder_email',
        ),
    ]
